version: '3.1'

services:
  front:
    image: front:1
    depends_on:
      - postgres
    ports:
      - 3000:3000
  apteka:
    image: apteka:1
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER:localhost
      - ADMINER_DEFAULT_USERNAME:postgres
      - ADMINER_DEFAULT_PASSWORD:postgres
      - ADMINER_DEFAULT_DATABASE:apteka
  postgres:
    image: postgres
    volumes:
      - postgres_data:/data
    environment:
      POSTGRES_DB: apteka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    expose:
      - "5432"
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local